project:
  name: quickstart-splunk-enterprise
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  splunk-enterprise:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      HECClientLocation: 10.0.0.0/16
      KeyName: taskcat-test
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      SSHClientLocation: 10.0.0.0/16
      SplunkAdminPassword: $[taskcat_genpass_10]
      SplunkClusterSecret: $[taskcat_genpass_10]
      SplunkIndexerDiscoverySecret: $[taskcat_genpass_10]
      WebClientLocation: 72.21.196.66/32
    regions:
    - us-west-1
    - us-east-2
    s3_bucket: ''
    template: templates/splunk-enterprise-master.template.yaml
